import { linkedList } from "./linkedList.js";

const list = linkedList();
list.prepend(4);
list.append(5);
list.append(6);
list.append(7);
list.prepend(3);
list.prepend(2);
list.prepend(1);
list.size();
list.headNode();
list.tailNode();
list.atNode(-2);
list.atNode(5);
list.atNode(2);
list.atNode(8);
list.pop();
list.pop();
list.contains(-3);
list.contains(5);
list.contains(20);
list.find(2);
list.find(3);
list.find(5);
list.insertAt(3, 34);
list.toString();
list.removeAt(3);
list.toString();
